version: "3.8"

services:
  jupyter:
    build: .
    volumes:
      - .:/src/neuralpredictors
    ports:
      - "8888:8888"
    env_file: .env
    entrypoint: ["jupyter", "lab", "--allow-root"]
  pytest:
    build: .
    volumes:
      - .:/src/neuralpredictors
    entrypoint: ["pytest"]
  python:
    build: .
    volumes:
      - .:/src/neuralpredictors
